### PR TITLE
Small change with the NumberFormat options

### PR DESCRIPTION
**Pull request by jaw162**
fix accidental negative $0 account balance

### CODE REVIEW

**Comment by jkbpvsc** [comment]
@jaw162 Can you provide a description of the issue?

**Comment by jaw162** [comment]
@jkbpvsc hi sorry I forgot to put that in there

**Comment by edgarpavlovsky** [comment]
Resolves #59

**Comment by edgarpavlovsky** [comment]
@jaw162 really appreciate the contribution! I noticed `+` shows up when value is positive - could we only show a sign when values are `<0`?

Screenshot 2023-02-21 at 1 01 52 AM

**Review by edgarpavlovsky — APPROVED** [review]

**Comment by edgarpavlovsky** [comment]
@jaw162 looks good! feel free to merge 😎

**Pull request merged**
