### PR TITLE
Add hotkeys for shortcuts

### PR DESCRIPTION
**Pull request by arihantbansal**
As per https://github.com/mrgnlabs/mrgn-ts/issues/148

### CODE REVIEW

**Review by edgarpavlovsky — COMMENTED** [review]
this feels great - i merged some conflicts to make it easy

a few points:

* can we support `CMD` for macs, same way `CTRL` is supported for windows / (i'm assuming linux?)
* i noticed if i'm focused in on a field (e.g. i `CTRL+1` into the first input field) `CTRL` no longer responds - it'd be nice to continue to be able to navigate with keystrokes after initial usage
* it'd be helpful to show some kind of hotkey gateway marketing here - something somewhere to show people that they hotkeys are available. thinking about tensor / superhuman comparables - is it worth showing _some_ of the badges by default? maybe with the `CMD` icon or something? open to thoughts here

**Comment by arihantbansal** [comment]
> this feels great - i merged some conflicts to make it easy
> 
> a few points:
> 
> * can we support `CMD` for macs, same way `CTRL` is supported for windows / (i'm assuming linux?)
> * i noticed if i'm focused in on a field (e.g. i `CTRL+1` into the first input field) `CTRL` no longer responds - it'd be nice to continue to be able to navigate with keystrokes after initial usage
> * it'd be helpful to show some kind of hotkey gateway marketing here - something somewhere to show people that they hotkeys are available. thinking about tensor / superhuman comparables - is it worth showing _some_ of the badges by default? maybe with the `CMD` icon or something? open to thoughts here

1. yes, i'll make it so that it interchanges easily.
2. that's because of default input element behaviour. i'll override it
3. yes, sounds good. I was thinking since ctrl/cmd will show the hotkeys, it's useful to have some dialog box or tooltip to let the user know about that.

**Comment by edgarpavlovsky** [comment]
> yes, i'll make it so that it interchanges easily.

dope, this feels good

> that's because of default input element behaviour. i'll override it

switching feels good, but i noticed i can't get to `CMD+10-12` because it's overridden by `CMD+1`. any thoughts on how to fix that? less trivial of a problem

> yes, sounds good. I was thinking since ctrl/cmd will show the hotkeys, it's useful to have some dialog box or tooltip to let the user know about that.

let me know thoughts on a notification letting users know about the hotkeys. maybe something we can put in the footer while we're redesigning it? cc @AminMusah as you're working on #144

**Comment by AminMusah** [comment]
> > yes, i'll make it so that it interchanges easily.
> 
> dope, this feels good
> 
> > that's because of default input element behaviour. i'll override it
> 
> switching feels good, but i noticed i can't get to `CMD+10-12` because it's overridden by `CMD+1`. any thoughts on how to fix that? less trivial of a problem
> 
> > yes, sounds good. I was thinking since ctrl/cmd will show the hotkeys, it's useful to have some dialog box or tooltip to let the user know about that.
> 
> let me know thoughts on a notification letting users know about the hotkeys. maybe something we can put in the footer while we're redesigning it? cc @AminMusah as you're working on #144

Added a tooltip in #174 but it currently contains dummy hotkeys atm, will need a list a of the new hotkey commands to populate it cc @edgarpavlovsky

**Comment by arihantbansal** [comment]
> > > yes, i'll make it so that it interchanges easily.
> > 
> > 
> > dope, this feels good
> > > that's because of default input element behaviour. i'll override it
> > 
> > 
> > switching feels good, but i noticed i can't get to `CMD+10-12` because it's overridden by `CMD+1`. any thoughts on how to fix that? less trivial of a problem
> > > yes, sounds good. I was thinking since ctrl/cmd will show the hotkeys, it's useful to have some dialog box or tooltip to let the user know about that.
> > 
> > 
> > let me know thoughts on a notification letting users know about the hotkeys. maybe something we can put in the footer while we're redesigning it? cc @AminMusah as you're working on #144
> 
> Added a tooltip in #174 but it currently contains dummy hotkeys atm, will need a list a of the new hotkey commands to populate it cc @edgarpavlovsky

Awesome! I'll share a list later, once I've resolved the issue with hotkey numbers > 10.

For now, you can add `Ctrl/CMD`. Holding the key down, it shows all the available hotkey combinations with badges.

**Comment by AminMusah** [comment]
> > > > yes, i'll make it so that it interchanges easily.
> > > 
> > > 
> > > dope, this feels good
> > > > that's because of default input element behaviour. i'll override it
> > > 
> > > 
> > > switching feels good, but i noticed i can't get to `CMD+10-12` because it's overridden by `CMD+1`. any thoughts on how to fix that? less trivial of a problem
> > > > yes, sounds good. I was thinking since ctrl/cmd will show the hotkeys, it's useful to have some dialog box or tooltip to let the user know about that.
> > > 
> > > 
> > > let me know thoughts on a notification letting users know about the hotkeys. maybe something we can put in the footer while we're redesigning it? cc @AminMusah as you're working on #144
> > 
> > 
> > Added a tooltip in #174 but it currently contains dummy hotkeys atm, will need a list a of the new hotkey commands to populate it cc @edgarpavlovsky
> 
> Awesome! I'll share a list later, once I've resolved the issue with hotkey numbers > 10.
> 
> For now, you can add `Ctrl/CMD`. Holding the key down, it shows all the available hotkey combinations with badges.

Fantastic! On it and will be on standby for the rest.

**Comment by AminMusah** [comment]
> > > > yes, i'll make it so that it interchanges easily.
> > > 
> > > 
> > > dope, this feels good
> > > > that's because of default input element behaviour. i'll override it
> > > 
> > > 
> > > switching feels good, but i noticed i can't get to `CMD+10-12` because it's overridden by `CMD+1`. any thoughts on how to fix that? less trivial of a problem
> > > > yes, sounds good. I was thinking since ctrl/cmd will show the hotkeys, it's useful to have some dialog box or tooltip to let the user know about that.
> > > 
> > > 
> > > let me know thoughts on a notification letting users know about the hotkeys. maybe something we can put in the footer while we're redesigning it? cc @AminMusah as you're working on #144
> > 
> > 
> > Added a tooltip in #174 but it currently contains dummy hotkeys atm, will need a list a of the new hotkey commands to populate it cc @edgarpavlovsky
> 
> Awesome! I'll share a list later, once I've resolved the issue with hotkey numbers > 10.
> 
> For now, you can add `Ctrl/CMD`. Holding the key down, it shows all the available hotkey combinations with badges.

Fantastic! On it and will be on standby for the rest.

**Review by edgarpavlovsky — APPROVED** [review]

**Pull request merged**
