### PR TITLE
add nightly connect

### PR DESCRIPTION
**Pull request by NorbertBodziony**
Add support for Nightly Connect - Open source bridge wallet that allows for remote connections, persistent sessions and push notifications. You can try it out with extensions and mobile wallet (currently only [nightly wallet](https://wallet.nightly.app/) but we are working on more support.

Docs - https://docs.connect.nightly.app/docs/
Nightly connect repo - https://github.com/nightly-labs/connect

### CODE REVIEW

**Comment by losman0s** [comment]
Hey there, very keen to integrate Nightly!
Question though: I see that the change is more involved than I would expect. Nowadays wallets generally adhere to the wallet standard and only need the dapp to whitelist.

**Comment by NorbertBodziony** [comment]
Hey @losman0s i see that you guys changed flow so there are no "passive" actions do you want me to refactor this PR to match it ?

**Comment by losman0s** [comment]
Hey sorry for that, I've been heads down fixing some stuff and forgot to process your PR before breaking it.
If you've got some bandwidth for that I'd appreciate it yes, otherwise I'll get to it at some point.
Key thing if possible is to really have the least amount of changes so I can make quick work of the review. This should be easier rn as I've run formatting on the whole codebase recently and that the wallet-related logic has been greatly simplified.

**Comment by NorbertBodziony** [comment]
@losman0s fixed and removed unnecessary code

**Comment by NorbertBodziony** [comment]
@losman0s bump

**Pull request closed without merging**
